[build-system]
requires = ["poetry"]
build-backend = "poetry.masonry.api"

[tool]
[tool.poetry]
name = "lunavl"
version = "0.0.0"
description = "Python interface for VisionLabs Luna platform"
authors = ["VisionLabs <m.limonov@visionlabs.ru>"]
repository = "https://github.com/matemax/lunasdk"
[tool.poetry.dependencies]
python = ">=3.6"
numpy = "*"
requests = "^2.22"
jsonschema = "^3.2"
[tool.poetry.dev-dependencies]
sphinx = ">=2.0.0"
pytest = ">=4.4"
pytest-subtests = "*"
sphinx-autodoc-typehints = "*"
pre-commit = "^1.18"
black = {version = "^18.3-alpha.0",allows-prereleases = true}

[tool.black]
line-length = 120
target-version = ['py37', 'py36', 'py35']
